title: CEFP2019 Ambassadors Programs Team
email: tbyhdgs@gmail.com
description:
  Diagrams for planning of CEFP group project
baseurl: "/cefp-group-project-plan"
url: "https://tobyhodges.github.io/"]
